/*
 * mobileControllerCfg.h
 *
 * Created: 08/07/2023 21:54:25
 *  Author: 20101
 */ 


#ifndef MOBILECONTROLLERCFG_H_
#define MOBILECONTROLLERCFG_H_

typedef enum
{
  	CAR_IN_SCANNING_STATE = 0,
	CAR_IN_MOVING_FORWARD_STATE,
	CAR_IN_MOVING_BACKWARD_STATE,
	CAR_IN_MOVING_ROTATE_LEFT_STATE,
	CAR_IN_MOVING_ROTATE_RIGHT_STATE, 
	CAR_IN_MOVING_STOP_STATE,
	EXIT
}ENU_systemModeStates;



#endif /* MOBILECONTROLLERCFG_H_ */