
#ifndef BIT_MATH_H_
#define BIT_MATH_H_



#define SET_BIT(REG,BIT_NUMBER) 	(REG |= (1<<BIT_NUMBER))
#define GET_BIT(REG,BIT_NUMBER)		((REG>>BIT_NUMBER)&1)
#define CLEAR_BIT(REG,BIT_NUMBER) 	(REG &= (~(1<<BIT_NUMBER)))
#define TOGGLE_BIT(REG,BIT_NUMBER) 	(REG ^=(1<<BIT_NUMBER))


#endif 